// frontend/src/components/recipe/RecipeDetail.vue
<template>
  <article class="recipe-detail--container">
    <loading-spinner v-if="isLoading"/>

    <recipe-ui class="recipe-form--wrapper">
      <section>
        <text-font size="22">{{ recipe.name }}</text-font>
        <div class="dotted mt-16 mb-16"/>
        <picture>
          <img src="https://picsum.photos/400/400" width="284" height="177" alt="음식 이미지 1"/>
        </picture>
        <div v-if="recipe.detailedIngredient.length > 0" class="pt-6">
          <span class="tags mr-6" v-for="(tag, index) of recipe.detailedIngredient" :key="index">
            {{ tag.name }}
          </span>
        </div>
      </section>

      <div class="dotted mt-16 mb-16"/>

      <section>
        <text-font size="20">요리 소개</text-font>
        <div class="dotted mt-16 mb-16"/>

        <text-font v-text="recipe.desc" class="recipe-detail--desc"/>

      </section>

      <div class="dotted mt-16 mb-16"/>

      <section>
        <text-font size="20">조리법</text-font>
        <div class="dotted mt-16 mb-16"/>
        <section v-if="recipe.steps.length > 0" class="recipe-detail">
          <text-font v-for="(item) of recipe.steps" :key="item._id" class="pb-10">
            {{ item.desc }}
          </text-font>
        </section>
      </section>

    </recipe-ui>
    <section class="recipe-detail__button--wrapper">
      <custom-button variant="primary" @click="historyBack">
        <text-font color="white">목록</text-font>
      </custom-button>
    </section>

  </article>
</template>

<script lang="ts">
import {Options, Vue} from "vue-class-component";
import {ins} from "@/lib/axios";
import RecipeUi from "@/components/ui/RecipeUi.vue";
import {Recipe} from "@/interfaces/recipe";
import Spinner from "@/components/common/Spinner.vue";

@Options({
  components: {
    RecipeUi,
  }
})
export default class RecipeDetail extends Vue {
  isLoading = true;
  recipe: Recipe.Info = {
    _id: '',
    desc: '',
    createdAt: new Date(),
    detailedIngredient: [],
    likes: [],
    name: '',
    modified: false,
    steps: [],
    user: '',
    updatedAt: new Date()
  };


  recipeId = '';

  created() {
    this.recipeId = this.$route.params.id as string;
    this.load();
  }

  private async load() {
    try {
      const {data} = await ins.get(`/recipes/detail/${this.recipeId}`);
      this.recipe = data;
      this.isLoading = false;
    } catch (e) {
      console.log(e)
    }
  }

  private historyBack() {
    this.$router.go(-1);
  }

}
</script>

<style scoped lang="scss">
.recipe-detail--container {
  width: 100%;
  padding: 3rem 0;

  .recipe-form--wrapper {
    margin: auto;
    max-width: 1000px;
  }

  .recipe-detail--desc {
    width: 100%;
    min-height: 100px;
    height: 100%;
    background-color: $white;
    border: 1px solid $line;
    border-radius: 8px;
    padding: 1em;
  }

  .recipe-detail {
    display: flex;
    flex-direction: column;
    width: 100%;
    min-height: 200px;
    height: 100%;
    background-color: $white;
    border: 1px solid $line;
    border-radius: 8px;
    padding: 1em;
  }

  .recipe-detail__button--wrapper {
    padding-top: 20px;
    display: flex;
    max-width: 1000px;
    justify-content: center;
    margin: auto;
  }
}
</style>

// client/src/components/recipes/RecipeDetail.tsx
import { useEffect, useState } from 'react'
import { useParams } from 'react-router'
import { useQuery, useQueryClient } from 'react-query'
import { axiosInstance } from '@libs/axios'
import { IRecipe } from '@interfaces/IRecipe'
import './RecipeDetail.scss'
import { Image } from '@components/common/image/Image'

export const RecipeDetail = () => {
  const [recipeId, setRecipeId] = useState('')
  const params = useParams()
  const queryClient = useQueryClient()

  useEffect(() => {
    if (params) {
      const { recipeNo } = params
      if (recipeNo) {
        setRecipeId(recipeNo)
        queryClient.prefetchQuery(['recipeDetail', recipeId], getRecipe)
      }
    }
  }, [recipeId, queryClient])

  const getRecipe = async () => {
    try {
      const { data } = await axiosInstance.get(`/recipes/detail/${recipeId}`)
      return data
    } catch (e) {
      console.log(e)
    }
  }

  const { data, isLoading, isError, isIdle } = useQuery<IRecipe.RecipeDetail>(
    ['recipeDetail', recipeId],
    getRecipe,
    {
      staleTime: 2000,
      keepPreviousData: true,
    }
  )

  if (isLoading || isIdle) return <div>Loading....</div>
  if (isError) return <div>ERROR</div>

  return (
    <main>
      <article className={'recipe'}>
        <div className={'recipe-detail--container'}>
          <section className="recipe-form--label">
            <div className="flex pb-16" />
          </section>
          <section className="recipe-detail--top">
            <picture className="recipe-detail__img--wrapper mb-16">
              이미지
            </picture>
            디스크립션
            <div className="recipe-detail-info--container">
              <section className="recipe-detail--title">
                <div>
                  <p>{data.name}</p>
                  <div className="pt-16 pb-16 tags--wrapper">
                    {data.detailedIngredient &&
                      data.detailedIngredient.map((tag, index) => {
                        return (
                          <span className="tags mr-6" key={index}>
                            {tag.name}
                          </span>
                        )
                      })}
                  </div>
                </div>
              </section>

              <section className={'ingredients-container'}>
                <div className="mb-10">
                  주재료
                  <hr />
                  {data.allIngredient &&
                    data.allIngredient[0].ingredients.map(
                      (ingredient, index) => {
                        return (
                          <div
                            className={'flex justify-between pb-10'}
                            key={`ingredients-${index}`}
                          >
                            <p>{ingredient.name}</p>
                            <p>{ingredient.unit}</p>
                          </div>
                        )
                      }
                    )}
                  양념
                  <hr />
                  {data.allIngredient &&
                    data.allIngredient[1].ingredients.map(
                      (condiment, index) => {
                        return (
                          <div
                            className={'flex justify-between pb-10'}
                            key={`condiments-${index}`}
                          >
                            <p>{condiment.name}</p>
                            <p>{condiment.unit}</p>
                          </div>
                        )
                      }
                    )}
                </div>
              </section>
            </div>
            <hr />
            {data.user && (
              <section>
                <div className="flex">
                  <picture>
                    <Image
                      src={
                        data.user.img ||
                        'https://4u-recipe.s3.ap-northeast-2.amazonaws.com/profile/profile.svg'
                      }
                      alt="테스트 이미지"
                    />
                  </picture>
                  <div className="flex-column justify-content-around pl-10">
                    <p>{data.user.name}</p>
                    <p>{data.user.introduce}</p>
                  </div>
                </div>
              </section>
            )}
          </section>
          <section className="recipe-detail--bottom mt-30">
            <p>레시피</p>

            <hr />

            {data.steps &&
              data.steps.map((step) => {
                return (
                  <>
                    <section className={'pb-10 recipe-step'} key={step._id}>
                      <span>{step.step}</span>
                    </section>
                    <section className={'recipe-detail--desc'} key={step._id}>
                      <span>{step.desc}</span>
                    </section>
                  </>
                )
              })}
          </section>
        </div>

        <section className="recipe-detail__button--wrapper">목록</section>
      </article>
    </main>
  )
}
